[package]
name = "steam-idled"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "daemon"
path = "src/lib.rs"

[[bin]]
name = "steam-idled"
path = "src/main.rs"

[dependencies]
protocol.workspace = true
steam.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
clap.workspace = true
steamworks.workspace = true
nix.workspace = true

[dev-dependencies]
tempfile = "3.17"
